### ISSUE TITLE
IndexError: list index out of range`

### ISSUE THREAD

**Issue by firstylemen** [chenwr727/lianjia_scrapy#1]
- [ ] `程序运行一段时间后出现这个报错，请问是什么原因。我修改了config.py中的city# sqlite config
SQLITE_FILE_PATH = "./db/house_jh.db"

# log config
LOGS_NUM = 0

# scrapy
SLEEP_TIME = 0.6
CITY = "jh"`

`2022-02-24 18:46:05,556 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:07,563 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103118510884.html
2022-02-24 18:46:07,936 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:09,625 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103118648540.html
2022-02-24 18:46:09,857 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:11,485 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103116199523.html
2022-02-24 18:46:11,860 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:13,562 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103119175931.html
2022-02-24 18:46:13,872 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:15,475 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103119208519.html
2022-02-24 18:46:15,700 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:17,380 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103119218540.html
2022-02-24 18:46:17,590 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:19,313 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103119142135.html
2022-02-24 18:46:19,499 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:21,248 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103119195516.html
2022-02-24 18:46:21,687 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
2022-02-24 18:46:23,317 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 72 ｜ Successfully get house by url https://jh.lianjia.com/ershoufang/103119208227.html
2022-02-24 18:46:23,721 ｜ INFO ｜ main.py ｜ getHouseByUrl ｜ 81 ｜ Successfully added house
Traceback (most recent call last):
  File "e:/PythonProject/lianjia_scrapy-master/main.py", line 133, in <module>
    main()
  File "e:/PythonProject/lianjia_scrapy-master/main.py", line 129, in main
    house.getData(max_page=max_page)
  File "e:/PythonProject/lianjia_scrapy-master/main.py", line 25, in getData
    self.getUrlsByPage(page)
  File "e:/PythonProject/lianjia_scrapy-master/main.py", line 47, in getUrlsByPage
    self.getHouseByUrl(url)
  File "e:/PythonProject/lianjia_scrapy-master/main.py", line 71, in getHouseByUrl
    des_content = self.getContentByTags(contents[5]("div", {"class", "row"}))
IndexError: list index out of range`

**Comment by chenwr727** [comment]
- 原因：
contents越界
- 修复：
getHouseByUrl函数更改如下：

`python`

    def getHouseByUrl(self, url):
        req = self.session.get(url)
        html = req.text
        sell_detail_str = re.findall("init\(([\s\S]*?)\);", html)[0]
        sell_detail = demjson.decode(
            re.sub("\$\.getQuery\(.*\)", "''", sell_detail_str)
        )

        soup = BeautifulSoup(req.text, "html.parser")
        contents = soup("div", {"class": "content"})
        base_content = {}
        transaction_content = {}
        des_content = {}
        try:
            base_content = self.getContentByTags(contents[2]("li"))
            transaction_content = self.getContentByTags(contents[3]("li"))
            des_content = self.getContentByTags(contents[5]("div", {"class", "row"}))
            LOGGER.info(f"Successfully get house by url {url}")
        except Exception as e:
            LOGGER.error(f"Failed to get house by url {url}: {e}")

        house_base = schemas.HouseBase(
            url=url,
            sell_detail=sell_detail,
            base_content=base_content,
            transaction_content=transaction_content,
            des_content=des_content,
        )
        crud.createHouse(self.db, house_base)
        LOGGER.info("Successfully added house")
